# pyproject.toml is the file that tells build tools (like pip 10+ and build)
# what system you are using and what is required for building. The default if this file is missing is to
# assume a classic setuptools build system, but it is better to be explicit; if you have a pyproject.toml file,
# you will be able to rely on wheel and other packages being present.

[build-system]
requires = [
    "setuptools>=42",
    "wheel"
]
build-backend = "setuptools.build_meta"

# build-system.build-backend is technically optional, but you will get setuptools.build_meta:__legacy__ instead if
# you forget to include it, so always include it. If you were to use a different build system, such as flit or poetry,
# those would go here, and the configuration details would be completely different than the setuptools configuration described below.
# See PEP 517 and PEP 518 for background and details.